//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Scoring.Models
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class scoringEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“scoringEntities”部分中的连接字符串初始化新 scoringEntities 对象。
        /// </summary>
        public scoringEntities() : base("name=scoringEntities", "scoringEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 scoringEntities 对象。
        /// </summary>
        public scoringEntities(string connectionString) : base(connectionString, "scoringEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 scoringEntities 对象。
        /// </summary>
        public scoringEntities(EntityConnection connection) : base(connection, "scoringEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<scoring_department> scoring_department
        {
            get
            {
                if ((_scoring_department == null))
                {
                    _scoring_department = base.CreateObjectSet<scoring_department>("scoring_department");
                }
                return _scoring_department;
            }
        }
        private ObjectSet<scoring_department> _scoring_department;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<scoring_employee> scoring_employee
        {
            get
            {
                if ((_scoring_employee == null))
                {
                    _scoring_employee = base.CreateObjectSet<scoring_employee>("scoring_employee");
                }
                return _scoring_employee;
            }
        }
        private ObjectSet<scoring_employee> _scoring_employee;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<scoring_results> scoring_results
        {
            get
            {
                if ((_scoring_results == null))
                {
                    _scoring_results = base.CreateObjectSet<scoring_results>("scoring_results");
                }
                return _scoring_results;
            }
        }
        private ObjectSet<scoring_results> _scoring_results;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 scoring_department EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToscoring_department(scoring_department scoring_department)
        {
            base.AddObject("scoring_department", scoring_department);
        }
    
        /// <summary>
        /// 用于向 scoring_employee EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToscoring_employee(scoring_employee scoring_employee)
        {
            base.AddObject("scoring_employee", scoring_employee);
        }
    
        /// <summary>
        /// 用于向 scoring_results EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToscoring_results(scoring_results scoring_results)
        {
            base.AddObject("scoring_results", scoring_results);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="scoringModel", Name="scoring_department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class scoring_department : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 scoring_department 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        public static scoring_department Createscoring_department(global::System.Int32 id)
        {
            scoring_department scoring_department = new scoring_department();
            scoring_department.Id = id;
            return scoring_department;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int32> value);
        partial void OnParentIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="scoringModel", Name="scoring_employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class scoring_employee : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 scoring_employee 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        public static scoring_employee Createscoring_employee(global::System.Int32 id, global::System.String name)
        {
            scoring_employee scoring_employee = new scoring_employee();
            scoring_employee.Id = id;
            scoring_employee.Name = name;
            return scoring_employee;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DepartmentId
        {
            get
            {
                return _DepartmentId;
            }
            set
            {
                OnDepartmentIdChanging(value);
                ReportPropertyChanging("DepartmentId");
                _DepartmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepartmentId");
                OnDepartmentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DepartmentId;
        partial void OnDepartmentIdChanging(Nullable<global::System.Int32> value);
        partial void OnDepartmentIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Role
        {
            get
            {
                return _Role;
            }
            set
            {
                OnRoleChanging(value);
                ReportPropertyChanging("Role");
                _Role = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Role");
                OnRoleChanged();
            }
        }
        private Nullable<global::System.Int32> _Role;
        partial void OnRoleChanging(Nullable<global::System.Int32> value);
        partial void OnRoleChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="scoringModel", Name="scoring_results")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class scoring_results : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 scoring_results 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="employeeId">EmployeeId 属性的初始值。</param>
        public static scoring_results Createscoring_results(global::System.Int32 id, global::System.Int32 employeeId)
        {
            scoring_results scoring_results = new scoring_results();
            scoring_results.Id = id;
            scoring_results.EmployeeId = employeeId;
            return scoring_results;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeId
        {
            get
            {
                return _EmployeeId;
            }
            set
            {
                OnEmployeeIdChanging(value);
                ReportPropertyChanging("EmployeeId");
                _EmployeeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmployeeId");
                OnEmployeeIdChanged();
            }
        }
        private global::System.Int32 _EmployeeId;
        partial void OnEmployeeIdChanging(global::System.Int32 value);
        partial void OnEmployeeIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Scores
        {
            get
            {
                return _Scores;
            }
            set
            {
                OnScoresChanging(value);
                ReportPropertyChanging("Scores");
                _Scores = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Scores");
                OnScoresChanged();
            }
        }
        private Nullable<global::System.Decimal> _Scores;
        partial void OnScoresChanging(Nullable<global::System.Decimal> value);
        partial void OnScoresChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ScoresSerializerId
        {
            get
            {
                return _ScoresSerializerId;
            }
            set
            {
                OnScoresSerializerIdChanging(value);
                ReportPropertyChanging("ScoresSerializerId");
                _ScoresSerializerId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ScoresSerializerId");
                OnScoresSerializerIdChanged();
            }
        }
        private global::System.String _ScoresSerializerId;
        partial void OnScoresSerializerIdChanging(global::System.String value);
        partial void OnScoresSerializerIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BeRatedEmployeeId
        {
            get
            {
                return _BeRatedEmployeeId;
            }
            set
            {
                OnBeRatedEmployeeIdChanging(value);
                ReportPropertyChanging("BeRatedEmployeeId");
                _BeRatedEmployeeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BeRatedEmployeeId");
                OnBeRatedEmployeeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _BeRatedEmployeeId;
        partial void OnBeRatedEmployeeIdChanging(Nullable<global::System.Int32> value);
        partial void OnBeRatedEmployeeIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ScoreTime
        {
            get
            {
                return _ScoreTime;
            }
            set
            {
                OnScoreTimeChanging(value);
                ReportPropertyChanging("ScoreTime");
                _ScoreTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScoreTime");
                OnScoreTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ScoreTime;
        partial void OnScoreTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnScoreTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Suggest
        {
            get
            {
                return _Suggest;
            }
            set
            {
                OnSuggestChanging(value);
                ReportPropertyChanging("Suggest");
                _Suggest = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Suggest");
                OnSuggestChanged();
            }
        }
        private global::System.String _Suggest;
        partial void OnSuggestChanging(global::System.String value);
        partial void OnSuggestChanged();

        #endregion
    
    }

    #endregion
    
}
