USE [master]
GO

/****** Object:  Database [scoring]    Script Date: 04/18/2014 18:41:36 ******/
CREATE DATABASE [scoring] ON  PRIMARY 
( NAME = N'scoring', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\scoring.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'scoring_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\scoring_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [scoring] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [scoring].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [scoring] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [scoring] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [scoring] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [scoring] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [scoring] SET ARITHABORT OFF 
GO

ALTER DATABASE [scoring] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [scoring] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [scoring] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [scoring] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [scoring] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [scoring] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [scoring] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [scoring] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [scoring] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [scoring] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [scoring] SET  DISABLE_BROKER 
GO

ALTER DATABASE [scoring] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [scoring] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [scoring] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [scoring] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [scoring] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [scoring] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [scoring] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [scoring] SET  READ_WRITE 
GO

ALTER DATABASE [scoring] SET RECOVERY FULL 
GO

ALTER DATABASE [scoring] SET  MULTI_USER 
GO

ALTER DATABASE [scoring] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [scoring] SET DB_CHAINING OFF 
GO


